image: node:12-alpine3.12
before_script:
  - npm install
  - npm install -g eslint

cache:
  paths:
    - node_modules/

test_eslint:
  script:
    - eslint 'src/**'
    - npm run test:ci
    - npm run test:coveralls
